#!/usr/bin/env bash
# Install nginx on your web-01

apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

sudo chown 755 /etc/nginx/sites-enabled/default


sed -i -e 's/listen [0-9]*;/listen 80 defaults server;/' /etc/nginx/sites-enabled/default 
echo "Hello World!" > /var/www/html/index.html
nginx
