#!/usr/bin/env bash
# creates a new 404 error page


sudo apt-get install -y nginx 

echo "Hello World!" > index.html

sudo mv index.html /var/www/html

echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;

   location = /404.html{
      internal;
   }
}" > default

sudo mv default /etc/nginx/sites-available/default

sudo service nginx restart
