#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chmod 755 /var/www/html/
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart

a="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$a|" /etc/nginx/sites-enabled/default
sudo service nginx restart


b="\n\terror_page 404 /404.html;"
c="\n\tlocation = /404.html {\n\t\troot /var/www/html/error/;\n\t\tinternal;\n}\n"

sudo mkdir /var/www/html/error
sudo chmod 755 /var/www/html/error
sudo echo "Ceci n'est pas une page" > /var/www/html/error/404.html

sudo sed -i "57s|.*|$b|" /etc/nginx/sites-enabled/default
sudo sed -i "60s|.*|$c|" /etc/nginx/sites-enabled/default

d="\t\tadd_header X-Served-By $HOSTNAME;\n\t}"
sudo sed -i "52s|.*|$d|" /etc/nginx/sites-enabled/default
sudo service nginx restart
