#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update -y
sudo apt-get install haproxy -y
sudo chown  "$USER":"$USER" /etc/haproxy/haproxy.cfg

sudo echo "
frontend my_frontend
    bind *:80
    mode http
    default_backend my_backend
backend my_backend
    balance roundrobin
    server 341982-web-01 18.207.112.206:80 check
    server 341982-web-02 54.89.195.83:80 check" >> /etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
