#!/usr/bin/env bash
# makes nginx listen on port 80
sudo ufw allow 'Nginx HTTP'
sudo sed -i '22i listen 80 default_server;listen [::]:80 default_server;' /etc/nginx/sites-enabled/default
sudo service nginx restart
