#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
# shellcheck disable=SC2173
echo $$ > /var/run/myscript.pid

trap clean_up 15
trap clean_up 9
trap clean_up 3
trap "echo Y U no love me?!" 2

clean_up()
{
	echo "I hate the kill command"
	rm -r /var/run/myscript.pid
	exit
}
while 'true'
do
	echo "To infinity and beyond"
	sleep 2
done
