#!/usr/bin/env bash
#fizzbuzz

i=1

while [ "$i" -ne 101 ]
do
	d3=$((i % 3))
	d5=$((i % 5))

	if [ "$d3" -eq 0 ] && [ "$d5" -eq 0 ];
	then
		echo "FizzBuzz"
	elif [ "$d3" -eq 0 ]
	then	
		echo "Fizz"

	elif [ "$d5" -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi

	((i++))
done
