#!/usr/bin/env bash
#fizzbuzz
i=1
while [ $i -le 100 ]
do
	d=$((i % 3))
	j=$((i % 5))

	if [ "$d" -eq 0 ] && [ "$j" -eq 0 ];
	then
		echo "FizzBuzz"
	elif [ "$d" -eq 0 ] && [ "$j" -ne 0 ];
	then
		echo "Fizz"
	elif [ "$j" -eq 0 ] && [ "$d" -ne 0 ];
	then
		echo "Buzz"
	else
		echo "$i"
	fi

	((i++))
done
