#!/usr/bin/env bash
# bash script that sets localhost and facebook.com to another Ip
cp /etc/hosts /etc/hosts.old
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2 locahost/' ~/hosts.new
echo -e "127.0.0.2 localhost\n8.8.8.8 facebook.com" >> ~/hosts.new
cp ~/hosts.new /etc/hosts
